name: PHP Quality Assurance
on: [push]
jobs:
  lint-php:
    uses: inpsyde/reusable-workflows/.github/workflows/lint-php.yml@main
    with:
      PHP_MATRIX: >-
        ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]
  coding-standards-analysis-php:
    needs: lint-php
    uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main
    with:
      PHPCS_ARGS: '--report=summary'
  static-code-analysis-php:
    needs: lint-php
    uses: inpsyde/reusable-workflows/.github/workflows/static-analysis-php.yml@main
    with:
      PSALM_ARGS: '--threads=3'
  tests-unit-php:
    needs: [ coding-standards-analysis-php, static-code-analysis-php ]
    uses: inpsyde/reusable-workflows/.github/workflows/tests-unit-php.yml@main
    with:
      PHP_MATRIX: >-
        ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]
