name: PHP Quality Assurance
on:
    push:
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    static-qa:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'skip qa') }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                    tools: cs2pr

            -   name: Install dependencies
                uses: ramsey/composer-install@v2

            -   name: Check code styles
                run: |
                    ./vendor/bin/phpcs -q --report-full --report-checkstyle="phpcs-report.xml"  --runtime-set testVersion 7.2- --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1
                    cs2pr --graceful-warnings phpcs-report.xml

            -   name: Check Psalm
                run: ./vendor/bin/psalm --output-format=github --no-cache

    unit-tests:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'skip tests') }}
        env:
            USE_COVERAGE: no
        strategy:
            fail-fast: true
            matrix:
                php-ver: [ '7.2', '7.3', '7.4', '8.0', '8.1' ]
                deps-mode: [ 'lowest', 'highest' ]
                include:
                    - php-versions: '8.2'
                      dependency-versions: 'highest'
                continue-on-error: ${{ matrix.php-versions == '8.2' }}

        steps:
            -   name: Update "USE_COVERAGE" env var based on matrix
                if: ${{ matrix.php-ver == '7.4' && matrix.deps-mode == 'highest' }}
                run: echo "USE_COVERAGE=yes" >> $GITHUB_ENV

            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-ver }}
                    ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
                    coverage: ${{ ((env.USE_COVERAGE == 'yes') && 'xdebug') || 'none' }}
                    tools: cs2pr, parallel-lint

            -   name: Check syntax error in sources
                if: ${{ (matrix.deps-mode == 'highest') }}
                run: parallel-lint ./src/ --checkstyle | cs2pr

            -   name: Install dependencies
                uses: ramsey/composer-install@v2
                with:
                    dependency-versions: ${{ matrix.deps-mode }}

            -   name: Run unit tests
                if: ${{ env.USE_COVERAGE == 'no' }}
                run: ./vendor/bin/phpunit --testsuite=unit ${{ ((env.USE_COVERAGE == 'yes') && '--coverage-html=coverage-report') || '--no-coverage' }}

            -   name: Upload coverage report
                uses: actions/upload-artifact@v2
                if: ${{ env.USE_COVERAGE == 'yes' }}
                with:
                    name: coverage-report
                    path: coverage-report/