name: PHP Functional Tests

on:
  push:
    paths:
      - '**workflows/php-functional-tests.yml'
      - '**.php'
      - '**phpunit.xml.dist'
      - '**composer.json'
  pull_request:
    paths:
      - '**workflows/php-functional-tests.yml'
      - '**.php'
      - '**phpunit.xml.dist'
      - '**composer.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip tests') }}
    strategy:
      fail-fast: true
      matrix:
        php-ver: [ '8.0', '8.1', '8.2', '8.3' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-ver }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: 'none'
          tools: cs2pr, composer:v2

      - name: Adjust Composer dependencies
        run: |
            composer remove --dev --no-update "inpsyde/php-coding-standards"
            composer remove --dev --no-update "vimeo/psalm"
            composer require --dev --no-update "composer/composer:^2"

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Run functional tests
        run: ./vendor/bin/phpunit --testsuite=functional --no-coverage
